// export const generators = [
//   {
//     id: 'G-0032',
//     name: 'Colombo-Keels',
//     lat: 6.9271,
//     lng: 79.8612,
//     power: '500 kW',
//     status: 'online',
//     temperature: '65°C',
//     batteryLevel: '80%',
//     coolantLevel: '90%',
//     acVoltage: '220V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0034',
//     name: 'Trincomalee-Keels',
//     lat: 8.5874,
//     lng: 81.2152,
//     power: '750 kW',
//     status: 'offline',
//     temperature: '70°C',
//     batteryLevel: '20%',
//     coolantLevel: '50%',
//     acVoltage: '210V',
//     anomalies: { status: 'normal', message: 'Low battery and coolant levels' },
//   },
//   {
//     id: 'G-0035',
//     name: 'Jaffna-Keels',
//     lat: 9.6615,
//     lng: 80.0255,
//     power: '300 kW',
//     status: 'online',
//     temperature: '60°C',
//     batteryLevel: '95%',
//     coolantLevel: '85%',
//     acVoltage: '225V',
//     anomalies: { status: 'warning', message: 'Slightly high temperature' },
//   },
//   {
//     id: 'G-0036',
//     name: 'Kurunegala-Keels',
//     lat: 7.4862,
//     lng: 80.3648,
//     power: '600 kW',
//     status: 'online',
//     temperature: '55°C',
//     batteryLevel: '70%',
//     coolantLevel: '80%',
//     acVoltage: '230V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0037',
//     name: 'Galle-Keels',
//     lat: 6.0535,
//     lng: 80.2200,
//     power: '400 kW',
//     status: 'offline',
//     temperature: '75°C',
//     batteryLevel: '30%',
//     coolantLevel: '60%',
//     acVoltage: '200V',
//     anomalies: { status: 'alarm', message: 'High temperature detected' },
//   },
//   {
//     id: 'G-0038',
//     name: 'Matara-Keels',
//     lat: 5.9485,
//     lng: 80.5353,
//     power: '350 kW',
//     status: 'online',
//     temperature: '62°C',
//     batteryLevel: '85%',
//     coolantLevel: '88%',
//     acVoltage: '222V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0039',
//     name: 'Nugegoda-Keels',
//     lat: 6.8700,
//     lng: 79.8900,
//     power: '420 kW',
//     status: 'online',
//     temperature: '58°C',
//     batteryLevel: '75%',
//     coolantLevel: '92%',
//     acVoltage: '228V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0040',
//     name: 'Rathmalana-Keels',
//     lat: 6.8200,
//     lng: 79.8700,
//     power: '680 kW',
//     status: 'offline',
//     temperature: '72°C',
//     batteryLevel: '15%',
//     coolantLevel: '45%',
//     acVoltage: '205V',
//     anomalies: { status: 'normal', message: 'Low battery detected' },
//   },
//   {
//     id: 'G-0041',
//     name: 'Kandy-Keels',
//     lat: 7.2906,
//     lng: 80.6337,
//     power: '310 kW',
//     status: 'online',
//     temperature: '63°C',
//     batteryLevel: '88%',
//     coolantLevel: '87%',
//     acVoltage: '223V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0042',
//     name: 'Negombo-Keels',
//     lat: 7.2088,
//     lng: 79.8380,
//     power: '550 kW',
//     status: 'online',
//     temperature: '67°C',
//     batteryLevel: '65%',
//     coolantLevel: '78%',
//     acVoltage: '218V',
//     anomalies: { status: 'warning', message: 'Moderate temperature rise' },
//   },
//   {
//     id: 'G-0043',
//     name: 'Batticaloa-Keels',
//     lat: 7.7300,
//     lng: 81.7000,
//     power: '470 kW',
//     status: 'offline',
//     temperature: '76°C',
//     batteryLevel: '25%',
//     coolantLevel: '55%',
//     acVoltage: '195V',
//     anomalies: { status: 'normal', message: 'High temperature and low voltage' },
//   },
//   {
//     id: 'G-0044',
//     name: 'Anuradhapura-Keels',
//     lat: 8.3114,
//     lng: 80.4037,
//     power: '390 kW',
//     status: 'online',
//     temperature: '61°C',
//     batteryLevel: '90%',
//     coolantLevel: '95%',
//     acVoltage: '230V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0045',
//     name: 'Polonnaruwa-Keels',
//     lat: 7.9400,
//     lng: 81.0188,
//     power: '620 kW',
//     status: 'online',
//     temperature: '59°C',
//     batteryLevel: '82%',
//     coolantLevel: '89%',
//     acVoltage: '227V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0046',
//     name: 'Badulla-Keels',
//     lat: 6.9934,
//     lng: 81.0550,
//     power: '340 kW',
//     status: 'offline',
//     temperature: '74°C',
//     batteryLevel: '18%',
//     coolantLevel: '48%',
//     acVoltage: '208V',
//     anomalies: { status: 'normal', message: 'Multiple issues detected' },
//   },
//   {
//     id: 'G-0047',
//     name: 'Ratnapura-Keels',
//     lat: 6.6828,
//     lng: 80.3995,
//     power: '510 kW',
//     status: 'online',
//     temperature: '64°C',
//     batteryLevel: '77%',
//     coolantLevel: '91%',
//     acVoltage: '221V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0048',
//     name: 'Gampaha-Keels',
//     lat: 7.0873,
//     lng: 80.0144,
//     power: '430 kW',
//     status: 'online',
//     temperature: '60°C',
//     batteryLevel: '85%',
//     coolantLevel: '86%',
//     acVoltage: '224V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0049',
//     name: 'Kalutara-Keels',
//     lat: 6.5831,
//     lng: 79.9593,
//     power: '700 kW',
//     status: 'offline',
//     temperature: '78°C',
//     batteryLevel: '12%',
//     coolantLevel: '42%',
//     acVoltage: '190V',
//     anomalies: { status: 'normal', message: 'Critical system failure' },
//   },
//   {
//     id: 'G-0050',
//     name: 'Puttalam-Keels',
//     lat: 8.0362,
//     lng: 79.8283,
//     power: '480 kW',
//     status: 'online',
//     temperature: '62°C',
//     batteryLevel: '80%',
//     coolantLevel: '90%',
//     acVoltage: '229V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0051',
//     name: 'Vavuniya-Keels',
//     lat: 8.7542,
//     lng: 80.4982,
//     power: '360 kW',
//     status: 'online',
//     temperature: '65°C',
//     batteryLevel: '73%',
//     coolantLevel: '83%',
//     acVoltage: '222V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0052',
//     name: 'Mannar-Keels',
//     lat: 8.9772,
//     lng: 79.9098,
//     power: '590 kW',
//     status: 'offline',
//     temperature: '71°C',
//     batteryLevel: '22%',
//     coolantLevel: '50%',
//     acVoltage: '207V',
//     anomalies: { status: 'normal', message: 'Low coolant detected' },
//   },
//   {
//     id: 'G-0053',
//     name: 'Mullaitivu-Keels',
//     lat: 9.2671,
//     lng: 80.8142,
//     power: '450 kW',
//     status: 'online',
//     temperature: '63°C',
//     batteryLevel: '88%',
//     coolantLevel: '87%',
//     acVoltage: '226V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0054',
//     name: 'Kilinochchi-Keels',
//     lat: 9.3803,
//     lng: 80.3983,
//     power: '670 kW',
//     status: 'online',
//     temperature: '60°C',
//     batteryLevel: '79%',
//     coolantLevel: '92%',
//     acVoltage: '230V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0055',
//     name: 'Hambantota-Keels',
//     lat: 6.1429,
//     lng: 81.1212,
//     power: '380 kW',
//     status: 'offline',
//     temperature: '75°C',
//     batteryLevel: '17%',
//     coolantLevel: '46%',
//     acVoltage: '198V',
//     anomalies: { status: 'normal', message: 'High temperature detected' },
//   },
//   {
//     id: 'G-0056',
//     name: 'Ampara-Keels',
//     lat: 7.2978,
//     lng: 81.6747,
//     power: '520 kW',
//     status: 'online',
//     temperature: '61°C',
//     batteryLevel: '84%',
//     coolantLevel: '89%',
//     acVoltage: '223V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0057',
//     name: 'Kegalle-Keels',
//     lat: 7.2513,
//     lng: 80.3463,
//     power: '460 kW',
//     status: 'online',
//     temperature: '64°C',
//     batteryLevel: '76%',
//     coolantLevel: '85%',
//     acVoltage: '219V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0058',
//     name: 'Monaragala-Keels',
//     lat: 6.8714,
//     lng: 81.3507,
//     power: '610 kW',
//     status: 'offline',
//     temperature: '73°C',
//     batteryLevel: '20%',
//     coolantLevel: '49%',
//     acVoltage: '204V',
//     anomalies: { status: 'normal', message: 'Multiple issues detected' },
//   },
//   {
//     id: 'G-0059',
//     name: 'Dambulla-Keels',
//     lat: 7.8742,
//     lng: 80.6511,
//     power: '330 kW',
//     status: 'online',
//     temperature: '62°C',
//     batteryLevel: '91%',
//     coolantLevel: '94%',
//     acVoltage: '228V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0060',
//     name: 'Sigiriya-Keels',
//     lat: 7.9570,
//     lng: 80.7597,
//     power: '570 kW',
//     status: 'online',
//     temperature: '60°C',
//     batteryLevel: '83%',
//     coolantLevel: '88%',
//     acVoltage: '225V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0061',
//     name: 'Nuwara Eliya-Keels',
//     lat: 6.9708,
//     lng: 80.7829,
//     power: '490 kW',
//     status: 'offline',
//     temperature: '76°C',
//     batteryLevel: '14%',
//     coolantLevel: '43%',
//     acVoltage: '192V',
//     anomalies: { status: 'alarm', message: 'Critical system failure' },
//   },
//   {
//     id: 'G-0062',
//     name: 'Ella-Keels',
//     lat: 6.8667,
//     lng: 81.0466,
//     power: '410 kW',
//     status: 'online',
//     temperature: '63°C',
//     batteryLevel: '87%',
//     coolantLevel: '90%',
//     acVoltage: '227V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0063',
//     name: 'Tangalle-Keels',
//     lat: 6.0240,
//     lng: 80.7971,
//     power: '650 kW',
//     status: 'online',
//     temperature: '61°C',
//     batteryLevel: '78%',
//     coolantLevel: '86%',
//     acVoltage: '224V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0064',
//     name: 'Mirissa-Keels',
//     lat: 5.9488,
//     lng: 80.4718,
//     power: '370 kW',
//     status: 'offline',
//     temperature: '74°C',
//     batteryLevel: '19%',
//     coolantLevel: '47%',
//     acVoltage: '199V',
//     anomalies: { status: 'normal', message: 'High temperature detected' },
//   },
//   {
//     id: 'G-0065',
//     name: 'Weligama-Keels',
//     lat: 5.9750,
//     lng: 80.4297,
//     power: '530 kW',
//     status: 'online',
//     temperature: '62°C',
//     batteryLevel: '85%',
//     coolantLevel: '91%',
//     acVoltage: '226V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0066',
//     name: 'Unawatuna-Keels',
//     lat: 6.0170,
//     lng: 80.2503,
//     power: '440 kW',
//     status: 'online',
//     temperature: '64°C',
//     batteryLevel: '80%',
//     coolantLevel: '87%',
//     acVoltage: '222V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0067',
//     name: 'Hikkaduwa-Keels',
//     lat: 6.1407,
//     lng: 80.1011,
//     power: '600 kW',
//     status: 'offline',
//     temperature: '72°C',
//     batteryLevel: '21%',
//     coolantLevel: '50%',
//     acVoltage: '206V',
//     anomalies: { status: 'normal', message: 'Low coolant detected' },
//   },
//   {
//     id: 'G-0068',
//     name: 'Bentota-Keels',
//     lat: 6.4250,
//     lng: 80.0000,
//     power: '320 kW',
//     status: 'online',
//     temperature: '61°C',
//     batteryLevel: '89%',
//     coolantLevel: '93%',
//     acVoltage: '229V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0069',
//     name: 'Beruwala-Keels',
//     lat: 6.4788,
//     lng: 79.9868,
//     power: '580 kW',
//     status: 'online',
//     temperature: '63°C',
//     batteryLevel: '82%',
//     coolantLevel: '88%',
//     acVoltage: '225V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0070',
//     name: 'Chilaw-Keels',
//     lat: 7.5758,
//     lng: 79.7953,
//     power: '470 kW',
//     status: 'offline',
//     temperature: '75°C',
//     batteryLevel: '16%',
//     coolantLevel: '44%',
//     acVoltage: '193V',
//     anomalies: { status: 'normal', message: 'Critical system failure' },
//   },
//   {
//     id: 'G-0071',
//     name: 'Panadura-Keels',
//     lat: 6.7132,
//     lng: 79.9047,
//     power: '400 kW',
//     status: 'online',
//     temperature: '62°C',
//     batteryLevel: '86%',
//     coolantLevel: '90%',
//     acVoltage: '228V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0072',
//     name: 'Moratuwa-Keels',
//     lat: 6.7730,
//     lng: 79.8816,
//     power: '640 kW',
//     status: 'online',
//     temperature: '60°C',
//     batteryLevel: '79%',
//     coolantLevel: '85%',
//     acVoltage: '223V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0073',
//     name: 'Dehiwala-Keels',
//     lat: 6.8390,
//     lng: 79.8650,
//     power: '510 kW',
//     status: 'online',
//     temperature: '64°C',
//     batteryLevel: '81%',
//     coolantLevel: '88%',
//     acVoltage: '226V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
//   {
//     id: 'G-0074',
//     name: 'Maharagama-Keels',
//     lat: 6.8490,
//     lng: 79.9265,
//     power: '360 kW',
//     status: 'offline',
//     temperature: '73°C',
//     batteryLevel: '23%',
//     coolantLevel: '48%',
//     acVoltage: '201V',
//     anomalies: { status: 'alarm', message: 'Multiple issues detected' },
//   },
//   {
//     id: 'G-0075',
//     name: 'Boralesgamuwa-Keels',
//     lat: 6.8420,
//     lng: 79.9010,
//     power: '550 kW',
//     status: 'online',
//     temperature: '61°C',
//     batteryLevel: '90%',
//     coolantLevel: '92%',
//     acVoltage: '227V',
//     anomalies: { status: 'normal', message: 'All systems operational' },
//   },
// ];


export const generators = [
  {
    id: 'G-0032',
    name: 'Colombo-Keels',
    lat: 6.9271,
    lng: 79.8612,
    power: '500 kW',
    status: 'online',
    temperature: '65°C',
    batteryLevel: '80%',
    coolantLevel: '90%',
    acVoltage: '220V',
    anomalies: {
      status: 'normal',
      message: 'All systems operational',
    },
  },
  {
    id: 'G-0034',
    name: 'Trincomalee-Keels',
    lat: 8.5874,
    lng: 81.2152,
    power: '750 kW',
    status: 'online',
    temperature: '68°C',
    batteryLevel: '85%',
    coolantLevel: '88%',
    acVoltage: '225V',
    anomalies: {
      status: 'normal',
      message: 'All systems operational',
    },
  },
  {
    id: 'G-0035',
    name: 'Jaffna-Keels',
    lat: 9.6615,
    lng: 80.0255,
    power: '300 kW',
    status: 'offline',
    temperature: '60°C',
    batteryLevel: '70%',
    coolantLevel: '85%',
    acVoltage: '218V',
    anomalies: {
      status: 'warning',
      message: 'Low battery level',
    },
  },
];